using UnityEngine;
using System.Collections;

public class AudioList : MonoBehaviour {
	public AudioSource Bgm;
	public AudioSource NormalButton;
	public AudioSource ShareButton;
	public AudioSource TapToStart;
	public AudioSource ChooseHero;
	public AudioSource HeroBroken;
	public AudioSource HeroFallInWater;
	public AudioSource HeroAlive;
	public AudioSource CountDown;
	public AudioSource PillarAppear;
	public AudioSource Diamond;
	public AudioSource Jump;
	public AudioSource Fall;
	public AudioSource Airplane;
	public AudioSource Cube;
	public AudioSource Alpaca;
	public AudioSource Cartoon;
	public AudioSource Chicken;
	public AudioSource Crab;
	public AudioSource Deer;
	public AudioSource Dinosaur;
	public AudioSource Dog;
	public AudioSource Dragon;
	public AudioSource Duck;
	public AudioSource Elephant;
	public AudioSource Fish;
	public AudioSource Flamingos;
	public AudioSource Giraffe;
	public AudioSource Lion;
	public AudioSource Mushroom;
	public AudioSource Penguin;
	public AudioSource Snail;
	public AudioSource Spider;
	public AudioSource Unicorn;
	public AudioSource Whale;
	public AudioSource Theme;
}
